### ISSUE TITLE
Pipeline describe/run doesn't work as expected

### ISSUE THREAD

**Issue by DhavalThkkar** [datajoely/modular-spaceflights#3]
I'm currently exploring all the pipelines inside this particular tutorial. 

```
kedro pipeline describe -v feature_engineering
kedro run --pipeline feature_engineering
```

These particular commands share an error stating that this particular pipeline does not exist. 
```Error: `feature_engineering` pipeline not found. Existing pipelines: [Data ingestion, Feature engineering, Modelling stage, Pre-modelling, Reporting stage, __default__]```

I'm guessing that it is just because the pipeline has been named as "Feature Engineering" in the pipeline registry.

Could you please confirm?

**Comment by datajoely** [comment]
Hey @DhavalThkkar you need to actually use the name provided by the error message with the quotes:

`kedr run --pipeline "Feature engineering"`
